#!/usr/bin/env python3
"""Bundle small ROS2/Gazebo demo artifacts for download from a server.

The bundle intentionally excludes datasets, ROS build folders, and cache files.
It keeps only source/config/docs plus runtime evidence generated by the verifier.
"""

from __future__ import annotations

import argparse
import tarfile
from pathlib import Path


DEFAULT_INCLUDES = [
    "README.md",
    "docs/ros2_gazebo_costmap_demo.md",
    "outputs/ros2_gazebo_costmap_demo_summary.md",
    "outputs/ros2_gazebo_runtime_handoff.md",
    "outputs/perception_to_planner_integration_status.md",
    "outputs/perception_to_planner_contract.md",
    "outputs/perception_planner_matrix.md",
    "outputs/ros2_demo_runtime_summary.md",
    "outputs/ros2_runtime_diagnostics.md",
    "outputs/ros2_demo_report_section.md",
    "outputs/tables/perception_to_planner_contract.csv",
    "outputs/tables/perception_planner_matrix.csv",
    "outputs/tables/multilidar_tello03_ouster_pointcloud_3d_bboxes.csv",
    "outputs/tables/ros2_demo_runtime_summary.csv",
    "outputs/tables/ros2_runtime_diagnostics.csv",
    "data/processed/depth_sample_3_5fps.npz",
    "outputs/ros2_demo_runtime",
    "outputs/figures/perception_to_planner_contract.svg",
    "outputs/videos/ros2_costmap_demo_astar.mp4",
    "outputs/videos/ros2_fused_perception_runtime_astar.mp4",
    "ros2_ws/src/uav_oda_ros2_demo",
    "scripts/setup_ros2_gazebo_server.sh",
    "scripts/check_ros2_server_preflight.sh",
    "scripts/run_ros2_costmap_demo.sh",
    "scripts/run_headless_ros2_runtime_video.sh",
    "scripts/verify_ros2_fused_perception_demo.sh",
    "scripts/verify_ros2_costmap_runtime.sh",
    "scripts/verify_ros2_costmap_all_modes.sh",
    "scripts/audit_ros2_fused_demo_status.py",
    "scripts/validate_costmap_mux_status_sample.py",
    "scripts/check_costmap_mux_status_validator.py",
    "scripts/summarize_ros2_runtime_evidence.py",
    "scripts/diagnose_ros2_runtime_failures.py",
    "scripts/write_ros2_demo_report_section.py",
    "scripts/render_ros2_costmap_demo_video.py",
    "scripts/render_perception_to_planner_contract_figure.py",
    "scripts/bundle_ros2_demo_artifacts.py",
    "scripts/audit_ros2_demo_status.py",
    "scripts/check_ros2_costmap_demo_static.py",
    "scripts/check_ros2_launch_contract.py",
    "scripts/check_ros2_mode_consistency.py",
    "scripts/check_perception_to_planner_contract.py",
    "scripts/check_perception_planner_matrix.py",
]

EXCLUDE_PARTS = {
    "__pycache__",
    ".pytest_cache",
    "build",
    "install",
    "log",
}


def _should_include(path: Path) -> bool:
    return not any(part in EXCLUDE_PARTS for part in path.parts)


def _iter_files(path: Path) -> list[Path]:
    if not path.exists():
        return []
    if path.is_file():
        return [path] if _should_include(path) else []
    return sorted(child for child in path.rglob("*") if child.is_file() and _should_include(child))


def bundle(output_path: Path, includes: list[str]) -> list[Path]:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    added: list[Path] = []
    with tarfile.open(output_path, "w:gz") as tar:
        for include in includes:
            for file_path in _iter_files(Path(include)):
                tar.add(file_path, arcname=str(file_path))
                added.append(file_path)
    return added


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path("outputs/ros2_demo_artifacts.tar.gz"))
    parser.add_argument("--include", action="append", default=[], help="Additional path to include.")
    args = parser.parse_args()

    includes = DEFAULT_INCLUDES + args.include
    added = bundle(args.output, includes)
    print(f"Wrote {args.output} with {len(added)} file(s)")
    for path in added[:30]:
        print(f"  {path}")
    if len(added) > 30:
        print(f"  ... {len(added) - 30} more")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
